const applyCssVars = (vars) => {
  console.dir(vars)
  document.documentElement.style.setProperty(
    '--test-color',
    vars.paletteBtnPrimary
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary',
    vars.paletteBtnPrimary
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-text',
    vars.paletteBtnPrimaryText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-hover',
    vars.paletteBtnPrimaryHover
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-active',
    vars.paletteBtnPrimaryActive
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-active-text',
    vars.paletteBtnPrimaryActiveText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-opacity',
    vars.paletteBtnPrimaryOpacity
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-disabled',
    vars.paletteBtnPrimaryDisabled
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-disabled-text',
    vars.paletteBtnPrimaryDisabledText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-border',
    vars.paletteBtnSecondaryBorder
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary',
    vars.paletteBtnSecondary
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-text',
    vars.paletteBtnSecondaryText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-text-hover',
    vars.paletteBtnSecondaryTextHover
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-hover',
    vars.paletteBtnSecondaryHover
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-active',
    vars.paletteBtnSecondaryActive
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-active-text',
    vars.paletteBtnSecondaryActiveText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-opacity',
    vars.paletteBtnSecondaryOpacity
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-disabled',
    vars.paletteBtnSecondaryDisabled
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-disabled-border',
    vars.paletteBtnSecondaryDisabledBorder
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-disabled-text',
    vars.paletteBtnSecondaryDisabledText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm',
    vars.paletteBtnPrimarySm
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-text',
    vars.paletteBtnPrimarySmText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-hover',
    vars.paletteBtnPrimarySmHover
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-active',
    vars.paletteBtnPrimarySmActive
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-active-text',
    vars.paletteBtnPrimarySmActiveText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-opacity',
    vars.paletteBtnPrimarySmOpacity
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-disabled',
    vars.paletteBtnPrimarySmDisabled
  )
  document.documentElement.style.setProperty(
    '--palette-btn-primary-sm-disabled-text',
    vars.paletteBtnPrimarySmDisabledText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm',
    vars.paletteBtnSecondarySm
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-text',
    vars.paletteBtnSecondarySmText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-hover',
    vars.paletteBtnSecondarySmHover
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-hover-text',
    vars.paletteBtnSecondarySmHoverText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-active',
    vars.paletteBtnSecondarySmActive
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-active-bg',
    vars.paletteBtnSecondarySmActiveBg
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-active-text',
    vars.paletteBtnSecondarySmActiveText
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-opacity',
    vars.paletteBtnSecondarySmOpacity
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-disabled',
    vars.paletteBtnSecondarySmDisabled
  )
  document.documentElement.style.setProperty(
    '--palette-btn-secondary-sm-disabled-text',
    vars.paletteBtnSecondarySmDisabledText
  )
}

export { applyCssVars }
